@host = http://localhost:8000
@baseurl = http://localhost:8000/api/v1

### Get user who id = 1
GET {{host}}/api/v1/user/info?id=1
Authorization: Bearer asdadadasdasfasfas

### add user
POST {{host}}/api/v1/user/add HTTP/1.1
content-type: application/json

{
  "name":"Maiiiiid",
  "email":"1111111111",
  "password":"maid",
  "role": 0
}


### update user by id
POST {{host}}/api/v1/user/update HTTP/1.1
Content-Type: application/json

{
  "id":7,
  "name":"test",
  "email":"zhp92owwdwooooo",
  "password":"zhp",
  "role": 0
}


### Login
# POST {{host}}/api/v1/user/login HTTP/1.1
POST {{baseurl}}/user/login HTTP/1.1
Content-Type: application/json

{
  "name": "admin",
  "password": "111"
}


### Register
POST {{baseurl}}/user/register HTTP/1.1
Content-Type: application/json

{
  "name": "test1",
  "password": "11111111111111"
}

